<!DOCTYPE html>
<html>
	<header>
		<?php $page_name = "Blog - What's In A Name"; ?>
		<title><?php echo $page_name; ?></title>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/header.php'; ?>
	</header>
	
	<body> 
		<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/navbar.php'; ?>
		<div class="container">
		<div class="blurb">
				
		<h1> What's in a name? </h1>

		<p> My earliest story is how my name was chosen. When I was born, my extended family gathered together and all gave advice to my parents. Rather than just choosing from among this multitude of options, my parents put it up to a vote. While some of my family wanted a nice, simple sounding name like 丁好 (Ding Hao), literally translating to "very good", ultimately two characters came up to a tie. Having no other choice, my parents put those two characters together, and 丁淳旸 (Ding Chunyang) was born. </p>

		<p>Looking back at it, this story seems mostly apocryphal, but it filled me with satisfaction. I am an first-generation immigrant, born in Shanghai, China, but raised in America. As a product of multiple cultures, the idea that even the most basic part of my identity could be chosen through a democratic process by Chinese relatives, appealed to me. After all, names hold power. </p>

		<p> I am born to 丁军 (Ding Jun) and 许静 (Xu Jing), two loving parents who immigrated to the United States at the turn of the millenium. My father, born on the Chinese Army Day, was given a suitable name to match; 军人 (jun'ren) translates directly to "soldier". Perhaps my paternal grandparents wanted their son, firstborn of his generation, to be as strong and brave as the military was. My mother's given name means almost the exact opposite. 安静 (an'jing) is often posted in libraries, reminding patrons to be quiet and respectful of one another. While this name may reflect my maternal grandparents wishes for a quiet and peaceful life, it by no means translates to meekness. Both my parents are courageous and loving, capable of so much. </p>

		<p> My own name is a bit more difficult to understand. </p>

		<p> Like my father, I am the eldest son of my generation in the 丁 (Ding) family. While it is <a href="https://forebears.io/earth/surnames"> globally a more common last name </a> than even the ubiquitous Smith in America, it set me apart while I grew up in the United States. Coming across another Ding felt like a rare treat, and when I first created a Facebook account, I excitedly sent friend requests to complete strangers who shared the same last name. It took a decade and a half before I came across what may be the most famous (or at least for me, the most relevant) 丁 - 丁肇中, or Samuel C. C. Ting. <a href="#note1">[1]</a> Dr. Ting is a MIT professor and physicist who earned the 1976 Nobel prize in physics for discovering a new subatomic particle. Since this particle was simultaneously discovered by another group, it is the only subatomic particle to have a two letter name: the J/Psi particle. Ting suggested the J name, and while this may be related to the earlier named K-meson, it isn't difficult to see that the capital letter J looks quite similar to the Chinese character 丁. Dr. Ting's <a href="https://www.nobelprize.org/prizes/physics/1976/ting/speech/"> Nobel acceptance speech </a> was the first to be delivered in Mandarin Chinese, and is short and sweet. Instead of the common Nobel lectures given today, his was just a hair above 200 words, exhorting the value of difficult, experimental work for students around the world. </p>

		<p> The first character of my name can be interpreted in a few different ways. While not exceedingly common, 淳 (chun) could mean honest and pure, or simple and uncomplicated. When describing names to other Chinese speakers, it is fairly common to use the individual characters in phrases, specifying which of many homonyms is the character of your name. I frequently used the phrase 淳朴 (chun'pu) to describe this first character, which in my mind had meant "hard working". This was an interpretation that I quite liked. Being born in the year of the ox, I had always visualized my zodiac animal as being a down-to-earth creature, built <a href="https://www.zenpencils.com/comic/71-oswald-chambers-mountains-and-valleys-2/">for the valleys</a>. rather than high places. It fit my personality, where I would prefer to think of myself as being more diligent than inherently smart. We tell ourselves these narratives to shape our own stories, but it seems that there must have been a mistranslation somewhere along the way. In fact, this phrase actually means pure and unsophisticated. Taken positively, it may refer to a naive and bright-eyed student; taken the other way, it can refer to a simpleton. </p>

		<p> For a long time, the second character of my given name, 旸 (yang), was not included in many dictionaries. When saying it to other people, it is often mistaken for a homonym: 阳 (yang), as in sun - 太阳 (tai'yang) - or sunlight - 阳光 （yang'guang). While being related to the same family of meanings, the character in <em>my</em> name is more specifically referring to the rising sun. It's a character that is symbolic of hope and the dawn of a new day, a looking towards the East. My childhood nickname also originated by repeating this character, creating 旸旸, which is what my parents still call me today. </p>

		<p> Putting these characters together created no new meaning, only sounds that are slippery and foreign to the American tongue. Chun is pronounced ch-w-un, and yang should instead rhyme with the word "gong". Both characters by themselves have the second, lifting tone, but when put together, the second character becomes more commonly spoken with the third tone, an almost sing-songy lowering and re-raising of the voice. This is very different from an English phonetic pronunciation of the name, a flatter, more nasally sounding word that usually ends up rhyming with "son-dang". </p>

		<p> Even I sometimes have trouble fitting in the Chinese pronunciation of my own name in an otherwise English sentence, and seem to unconsciously switch between the two. I sympathize, because there is no good reason in English for a "ny" to be smack dab in the middle of this foreign word. Many text-to-speech synthesizers do their best and give my name three syllables, creating an extra syllable like the first part of "nice" to form "choo-ni-ang". I was startled the first time I heard this pronunciation when getting into an Uber - it is not every day that your taxi driver's phone creates a new way to form your own name at you. Yet, blaming English for not obeying Chinese pinyin rules sometimes seems as useless as blaming a fish for not climbing trees. [2]</p> 

		<p> As a child in Ohio, my parents freely had teachers and friends call me by my childhood nickname, Yangyang. The repetition of the same four letters seemed to at least make it obvious that this was a nickname. It wasn't until I had entered primary school that I started going by my full name, and was inadvertently renamed. There, my Tennessee peers had much trouble with this strange child's first name. There was no problem with my last name at all - ding-dong is easy enough to remember, and being Chinese, it can easily be coupled to the sound of a reverberating gong. Kids can be cruel to each other, and I remember being chased around the playground with the sing-song phrase, "chun-yang ding dong the third, bwangggg" being repeated by my tormentors. <a href="#note3">[3]</a> Eventually, this long phrase was just too wordy for the classroom, and a third grade classmate decided to take it on himself and give me another name. Taking the first five letters of my full name, he just added another "n", and out came Chunny. It was easy. Short and memorable, my friends rapidly adopted it. I was too young to understand the revulsion my parents had for this foreign renaming. Chunyang represented culture and their true home, whereas Chunny was a meaningless collection of sounds. But as a socially-awkward kid, having an easy-to-say, easy-to-remember name was everything. </p> 

		<p> Chunny is just a bit goofy, and it easily rhymes with so many other words. As my family continued to wander across America, my nickname became the easiest foothold to introduce myself in any new setting. "Hi, my name is Chunny - it rhymes with sunny, funny, bunny, money... you get the picture." I ran for - and won - student council in high school by leveraging my funny name, taping concierge bells onto posters, reminding my peers to "Vote for the *Ding*". <a href="#note4">[4]</a> Even as a twenty year old college student attending an international quantum computing summer school, I doodled little cartoons of the words that rhymed with my nickname on my nametag during lecture. I no longer wanted to be the bookish nerd, reading alone in the corner anymore, but to be surrounded by friends who I could chat and laugh together with. </p>

		<p> Is it just serendipity that the easiest rhyme of my nickname, Chunny to sunny, is so close to the meaning of the Chinese character in my name? If so, it's no more of a coincidence that the auto-correction function of most phones will typically assume that you mean "chubby" or "chunky" when typing "chunny", two phrases that I was also frequently called as a kid. I laugh and shrug it off these days, because like the kids from my elementary school, these mistakes are not usually made in bad faith. It is simply a product of growing up in a mixed cultural environment. I still yearn to be simultaneously building up this American community while holding on to my Chinese heritage. Can I not hold on to both nickname and name with equal amounts of fervor? <a href="#note5">[5]</a> In practice, my flawed compromise is to insist that any formal, written version of my name to be "Chunyang" while simultaneously encouraging friends to call me Chunny in conversations and messages. </p> 

		<p> For most people, names are the closest things to us that we cannot choose, only receive. Only popes and immigrants have the luxury of defining that most basic part of identity. In November 2016, I was given that choice when becoming a naturalized American citizen. As the xenophobia that defined Trump's rise grew in volume, it might have been easier to hide under a Anglicized, inoffensive version of myself. But to do so would be to sever my own roots; I cannot do that. However, I do expect one further change to my name in the near future: I look forwards to the day that I will have the same title as my father, and be referred to as Dr. Ding with my PhD in hand. </p> 

		<p> We write our own stories, and there is no doubt in my mind that even this basic narrative will be viewed differently as my life continues.</p> 
		
		<p> But for now, this is how I choose to define myself.</p> 
		
		 
		<p> <a id="note1">[1]</a>: Ting and Ding are both romanticizations of the same character. While Ding is the current romanticization under the standardized <a href="https://en.wikipedia.org/wiki/Pinyin"> Hanyu Pinyin system </a> adopted after the Chinese romanticization, the older <a href="https://en.wikipedia.org/wiki/Wade%E2%80%93Giles"> Wade-Giles system </a> used the romanticization Ting. Taiwan, where Samuel Ting was raised, mostly used the Wade-Giles system until a few decades ago. These different systems are the same reason why many older Chinese institutions, such as Peking University, are different from their current pinyi romanticization. </p> 

		<p> <a id="note2">[2]</a>: While I have taken this somewhat cavalier attitude towards pronounciations of my own name, I do not want to convey that such an attitude is the norm for immigrants. Many notable actors and actresses, including <a href="https://www.youtube.com/watch?v=3t3YhWQppAw">Hasan Minhaj</a> and <a href="https://www.improper.com/arts-culture/the-eyes-have-it/">Uzoamaka Aduba </a> have spoken on this point: if Western tongues have become familiar with difficult Russian (Dostoyevsky), Greek (Pythagoras), and even fictional (Daenerys Targaryen) names, then why can't they pronounce our names? It points towards the innate duplicity in saying "Oh, but your name is just so hard to pronounce!" It is not a matter of if you can pronounce a name, but instead, of if you want to take the time and pronounce a name. </p>
		
		<p> <a id="note3">[3]</a>: "The third" comes from either a very odd understanding of Chinese empires and dynasties, or - more likely - the fact that my last name was alphabetically the third in that class; we were given these numbers to help our teacher with easily sorting graded assignments). </p>
		
		<p> <a id="note4">[4]</a>: Kids would slap the bells as they walked by in the hallways, sending those dings! down the hallway. My teachers were less than amused, and in about two days, every bell was torn off. Undeterred, I also incorporated my name into Jessie J's "Price Tag", singing in a Facebook video ad "It's not about the Chunny, Chunny, Chunny..." to win votes. </p> 
		
		<p> <a id="note5">[5]</a>: I am still proud of my nickname of Chunny today. Despite it's odd origins, I feel like it is something that I have made my own. It's not just that I end up getting great Search Engine Optimization by doing so, it's that this name is as representative of my immigrant story as anything else. However, all of this is with the caveat that I have grown up surrounded by supportive friends who have indeed respected that portion of my identity; I imagine this narrative would be very different if our family continued to live in a place where I was often the only Chinese-American student in the classroom. So again, I cannot say that such a view would be representative of other immigrant narratives; I can only tell my own. </p> 

		
		
		<p> <a href="/2020/05/01/the-four-cs">Previous</a> | <a href="/blog">Return to main</a></p>

		</div>
		</div>
	<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/webcounter.php';
		$access_number = visitor($page_name); ?>
	<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/footbar.php'; ?>
	</body>
</html>