<?php include $_SERVER['DOCUMENT_ROOT'].'/header.php'; ?>
<div class="container">
	<div class="blurb">
	
<center> <h1> July 31 -- Acts 16 </h1> </center>

<p> Hello! Thank you for the reference about Narnia Jonh, that was interesting to read :) </p>

<p> How you understand Paul makes sense to me and I also was unsure about how it was deliberated which laws should be included! For whether circumcision should be required to be in the church: It wasn't mentioned in Acts 15, but I thought it might also be relevant that circumcision marked the covenant that God made with Abraham and the generations to follow him (Genesis 17). During the last supper, Jesus explains that there is a new covenant through his blood (Luke 22:20). The covenant through Abraham required circumcision to be in community and was meant for Abraham's household, but the new covenant is meant for both his household and the gentiles. I might not be so grounded from the passage here, but the mark of the new covenant could be receiving the Holy Spirit (which the gentiles mentioned had). Then, the new covenant in place wouldn't require circumcision as it no longer functions to mark a person in God's covenant. </p>

<p> Though for why some laws are asked to be kept some are not, it does sound like practical considerations like you were mentioning. Maybe the points on eating were judged especially counterproductive to unity in the public between gentiles and those of Jewish heritage? Again like you mentioned, they do say that it seemed good to the Holy Spirit, so we might infer that their judgement was guided. It's also true though that I don't understand the nuances that well! </p>

<p> On Eric's experiment for trying to get a sense of the source of our thoughts &amp; feelings: I think I was partly aware, but placing focus on it did make me feel more responsible. A practical step that I tried to take is to try to avoid actions are postures that fed those, which was somewhat helpful. Although I feel that there are good intentions in me, there are certainly those that are called upon weaknesses such as fear or lust that readily produce emotions or thoughts that I believe not to be righteous. I think the passage from Romans acknowledges this nature, "We know that the law is spiritual; but I am unspiritual, sold as a slave to sin. I do not understand what I do. For what I want to do I do not do, but what I hate I do... So I find this law at work: Although I want to do good, evil is right there with me. For in my inner being I delight in God’s law; but I see another law at work in me, waging war against the law of my mind and making me a prisoner of the law of sin at work within me. What a wretched man I am! Who will rescue me from this body that is subject to death? Thanks be to God, who delivers me through Jesus Christ our Lord!" (Romans 7:14 ... 25) The next chapter elaborates by describing life through Spirit, "Those who live according to the flesh have their minds set on what the flesh desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires. The mind governed by the flesh is death, but the mind governed by the Spirit is life and peace" (Romans 8:5-6) What I gather is that the flesh is sinful, but we have minds that can obey the flesh or be guided by the Spirit. I can't see my weaknesses disappearing, but I think this is a picture that I can work towards. Then the Spirit aids in our struggles to follow God "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans" (Romans 8:26) So maybe the work that we have is about being receptive to the Spirit and heed His guidance. Sorry this got long! Just wanted to put some thoughts down because Eric was telling his thoughts on heart/thought &amp; the indwelling of the Holy Spirit! </p>

<p> Acts 16 very quick summary: Paul meets with Timothy, is called to go to Macedonia, is directed by the Spirit throughout his journey, is thrown into prison &amp; released and shares the gospel throughout. What is striking to me is the way unpredictable way in which Paul's experiences leads to the salvation of many people such as the jailer who witnesses a miracle of God and His mercy. </p>

<p> Also of note is the slave who shouted out that “These men are servants of the Most High God, who are telling you the way to be saved.” (Acts 16:8) Like how the evil spirits knew who Jesus was, the spirit inside the slave also knew.  Paul's reaction in this way: "She kept this up for many days. Finally Paul became so annoyed that he turned around and said to the spirit, 'In the name of Jesus Christ I command you to come out of her!' At that moment the spirit left her." (Acts 16:18) Then, there were no further explanations of what happened to the slave. Three questions come to mind. 1) Why did Paul get annoyed? 2) Is being annoyed a right manner in which to call upon the authority of Jesus? 3) The slave knew who Paul was and the truth of what he preached. Was she saved? If not, why not? I believe all three questions might be interrelated, so knowing any could help with the others! It might have something do with the statement not reaching the heart of the person. Even if she is more certain of the truth than a believer, she might not have received the Holy Spirit (I guess she already had a spirit within her?). Perhaps Paul was rightfully angry at the Spirit because it came in the way of doing God's work so that exorcising it in his annoyed state was justified. Very speculative here! I'd welcome any thoughts! </p>

<p> Also doing well and I was finally notified that my OPT application was approved! Would you all be interested in calling in the next couple of weeks? </p>

<p> Best, </p>
<p> Tuna </p>

<center> <p> <a href='/acts/Acts15'>Previous</a> | <a href='/acts/acts'>Back to Main</a> |  <a href='/acts/Acts17'>Next</a></p> </center>

</div>
</div>
<?php include $_SERVER['DOCUMENT_ROOT'].'/footer.php'; ?>