<!DOCTYPE html>
<html>
	<header>
		<?php $page_name = "Blog - My Blog Pt 2"; ?>
		<title><?php echo $page_name; ?></title>
		<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/header.php'; ?>
	</header>
	
	<body> 
		<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/navbar.php'; ?>
		<div class="container">
		<div class="blurb">

		<h1> The Story of My Blog - Pt. 2 </h1>
		
		<p> <em> A continuation - in spirit - of <a href="https://seattlechunny.wordpress.com/2015/04/10/the-story-of-my-blog/">this post from 2015</a>. </em> </p>

		<p> When I was young, I wanted everyone to hear me. That desire didn't come from any lack of attention from my parents, for I was a spoiled only child, nor was I missing engagement from my teachers, who I believe mostly adored my quiet and bookish traits. But those same traits led me to be a bit of an outcast as a kid in elementary and middle school, staying inside during recess, not knowing the first thing about football or pop culture. I had a very limited friend circle, and even with them, felt limited in my ability to physically "hang out" with them. My frequent moves as a kid definitely didn't help; I would start all of my school years through 3rd grade in a completely new, completely different environment. In those days, I would turn externally towards books - Harry Potter, Percy Jackson, Artemis Fowl - to try to understand the world, and then internally to my diaries and journals to construct my own world. </p>

		<p> When Daniel introduced Facebook to me in 2008, initially to play Farmville and Mafia Wars, I was immediately hooked. My early statuses bounced off the walls, broadcasting the mundane ("is going to br celebrating lent even though he isnt a catholic or whatever" - March 7, 2009), to what I thought was witty ("is hating how statuses stay on even after a couple of weeks. so if you wrote "I'm going to sleep" at 10 today and you don't change it for a month, well, you know what I mean" - August 13, 2009) to the undecipherable ("is woah!!! Snow!!!!!!!!!!!!!!!!" - February 22, 2009)<a href="#note1">[1]</a>. I am, as Gretchen McCulloch might say, a digital native, having formed most of my formidable years hanging out online rather than shopping malls. I had also felt more <i> comfortable </i> talking to my friends via digital chats, whether it was because I felt like my childhood speech impediment made it difficult for me to communicate, or because I thought that I was too boring of a person to talk to, and thus needed to rehearse my words, or because I wanted to be the person with an answer for anything. I was reasonably quick at typing, so having digital conversations in an age where not that many people could touch type meant that, for once, I would be the one with the first and last words. </p>

		<p> At that time, I had an inkling of how digital privacy worked; I knew that posting private information on a public platform was not a good idea, especially since I had lied about my age to create an account in the first place. I knew that pictures could be dangerous, hence why my profile picture was what I termed a "super ultra dodecahedron" for many months. But beyond that, the internet felt like a playground. Things were wild and free; Facebook quizzes were all the rage, and Jayisgames kept me amused with <del>cheap</del>free flash games. </p>

		<p> Skip forwards a few years, and my high school self was even more self-conscious, even more self-aware. Social media was no longer for random thoughts, but for polished presentations. Most of your "friends", after all, haven't spoken to you in years and years. Moreover, social media began to feel permanent. At any point, someone can skip back into your timeline, dig up an old post, and bring that repressed memory back. At the same time, Wolfram|Alpha had a particularly insidious feature of analyzing your Facebook profile. Before Cambridge Analytica, Wolfram|Alpha would allow you to enter your Facebook profile and spew out statistics: the time of day when you posted most frequently, your Facebook friends and how they connected to each other, and - most crucially - a tally of how many total likes and comments you have ever received on all of your combined posts and pictures. Oh, and one more thing. This information was not limited to your own profile, but to Any. Person's. Profile. Meaning that my insecure self would spend hours and hours comparing and contrasting, looking at my more popular friend's profiles, thinking of ways to engineer posts that would rack up the most number of likes. </p>

		<p> The disease of wanting to only be seen as knowledgeable and popular spread, from Facebook to Twitter, Tumblr to Wordpress. One by one, all of the digital platforms that I once enjoyed became toxic cesspools, filled with hidden pitfalls. That period also brought to mind the idea of the digital scandal; that politicians and scientists could be criticized for some seemingly harmless joke made several years prior where the norms and mores of the time permitted it. I was terrified of saying the wrong thing and be seen as intolerant, or angry, or ignorant. <a href="#note2">[2]</a> </p>

		<p> Of course, all of this stemmed from a root of having a very specific view of what my public persona would be. Like the childhood heroes that I read about in YA fiction, I wanted to be invincible, to be wise, to be admired - all of the traits that I felt was missing from my (even) younger self. Sure, I wanted to be emotionally available as well, but only in small, measured doses. A controlled amount of randomness, if you will. In essence, I wanted to be popular, but my idea of what would make me popular was so superficial and twisted. Being popular meant getting lots of likes on my Facebook posts - so I would make sure to only post things that would make me look witty, punny, or fun. Being popular meant receiving lots of messages late at night, so I would offer to help out friends on their homework for free, pushing myself further and further into a hole. Being popular meant being a kind and caring person, so I would (try to) shoulder other people's issues without speaking about any of my own. And above all else, being popular meant being in control, so I would seek to be admin of this group and leader of that extracurricular club, providing guidance and input even when none was needed. </p>

		<p> All of this led to a significant crash for myself in 2015, where I suddenly found myself on the outside looking in once again. Through all of those friendships, I felt like I kept everyone at least an arm's length away, resulting in me suddenly being put on the wayside when my usefulness expired. I didn't know who I could turn to. More concerning, for all that I had written and reflected on, I still didn't know who I was. I had so perfectly crafted a persona for myself that I didn't know what was a genuine interest, and what was an interest I had persuaded myself that I ought to like. Entering college, the personal crisis continued and deepened, feeling afloat and drifting between people who seemed like the ideal version of who I wanted to be. Given all of this, I went silent. I stopped posting on any social media, disliking the way that I looked and the trivial things that I had accomplished. I was fearful of bragging again, perceiving (partially correctly) that this kind of behavior was what kept me from forming true connections. </p>

		<p> This is the part of the narrative arc where the author should make a sudden recovery, discovering their <i>True Purpose</i>, finding themselves once again, and recovering forever more. Yet even the subversion of that arc - the continued, steady work of refining who I am and who I am not - is not fully true. Indeed, I did start to form closer, personal friendships, with people who I could truly rely on and who I felt could truly rely on me. I cut away parts of me that were leading me towards jealousy, and tried to develop hobbies for their own sake and for my own curiosity. But I frequently lapsed into old patterns, spiraling into panic, and refusing to acknowledge what was wrong. In those worst days, I would still write - angrily, madly - but only on notepad documents to myself <a href="#note3">[3]</a>, hidden away in some locked file folder somewhere. I no longer wanted people to see the worst of me, because I have seen it and found it too bitter. </p>

		<p> And yet, here we are. 23 years old, and still seeking to understand what is a reasonable thing to be putting out in the open internet. I think for the moment, I still do feel a necessity to have an airgap between the writing that I do for myself, and the writing that I do for others. Being, the writing that I do for myself is akin to a diary. They involve personal matters that may hurt or harm the people and things that I care about in the world if they were fully released, unfiltered and unedited. The intent for writing such works is catharsis, where my mind would be cleaner without dwelling on those thoughts. The writing that I do for others is necessarily for some audience to eventually consume. It is a reflection of my aspirational self. While it may never be the "so random!" thoughts that I had posted in my awkward adolescence, I do seek to be more genuine in the words I write. </p>

		<p> Why do I write any of this at all, especially on a platform that I hope to be a professional face for me? Simply because every story needs some kind of origin, and this is where I stand today. From here, I can only move forwards, diving deeper into the vast unknown.<a href="#note4">[4]</a> </p> 

		<p> <a id="note1">[1]</a>: NB: This is back in the days where Facebook would automatically append your name to the beginning of statuses, such that it would read "Chunyang Ding is woah!!! Snow!!!!!!!!!!!!!!!!". This does not matter at all today, but I did still want to document it. </p>

		<p> <a id="note2">[2]</a> "Just saying, even when I know that nobody is going to read this, I still hesitate to write. If this was a  hand-written piece, you would see scribble marks and even big sections marked out! This is because I don’t want to offend, hurt, or even tarnish my reputation. Often, I’ll read over what I have just written and think that it was too harsh, and just scratch the entire paragraph!" - February 3, 2011 </p>

		<p> <a id="note3">[3]</a> science is spending 2 hours downloading an experiment file to find that the file is corrupted :C // // oh wait did i say science? i meant HELL. - August 25, 2016 </p>

		<p> <a id="note4">[4]</a> Sorry, I just realized that I got to the end of this post and had not even properly defined what I set out to say. This blog, if not already obvious, will be for reflections that I hope would be fairly long-lasting in intent. I have recently discovered that I am growing old and is now full of opinions about all kinds of things. While I would like to share those opinions with you face-to-face, having a semi-public platform to write still feels incredibly attractive to me, partially for the reasons I have discussed above, and partially for reasons that I do not yet understand in myself. </p> 
		
		<p> <a href="/2020/02/04/2020-plan">Previous</a> | <a href="/blog">Return to main</a> | <a href="/2020/04/01/progress-update"> Next </a> </p>

		</div>
		</div>
	<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/webcounter.php';
		$access_number = visitor($page_name); ?>
	<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/footbar.php'; ?>
	</body>
</html>